# Generated by Django 4.2.26 on 2025-12-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del producto.', max_length=100)),
                ('codigo', models.CharField(help_text='Código único o SKU del producto.', max_length=20, unique=True)),
                ('stock', models.IntegerField(default=0, help_text='Cantidad actual en inventario.')),
                ('stock_minimo', models.IntegerField(default=1, help_text='Nivel mínimo para generar alerta de reposición.')),
                ('stock_maximo', models.IntegerField(default=9999, help_text='Nivel máximo deseado en inventario.')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de costo unitario.', max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
