# Generated by Django 4.2.26 on 2025-11-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nombre_usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('celular', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('clave', models.TextField()),
                ('cargo_trabajo', models.CharField(max_length=50)),
            ],
        ),
    ]
