# Generated by Django 4.2.26 on 2025-12-09 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha_movimiento'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Indica el motivo del movimiento: compra, merma, robo, reposición, etc.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Aumento de Stock)'), ('SALIDA', 'Salida (Disminución de Stock)')], max_length=10, verbose_name='Tipo de Movimiento'),
        ),
    ]
