# Generated by Django 4.2.26 on 2025-11-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('stock_antes', models.IntegerField()),
                ('stock_despues', models.IntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado')),
            ],
        ),
    ]
